In [33]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

# Example: from string to integers to binary features

In [11]:
D = [['dog','Paul'],['dog','Mark'],['cat','John'],['dog','Paul'],['mouse','Paul'],['cat','Mark']]

In [56]:
df = pd.DataFrame(columns=['animal','name','city'])
df['animal']=['dog','dog','cat','dog','mouse','cat','cat']
df['name']=['Paul','Mark','John','Paul','Paul','Mark','Mark']
df['city']=['Rome','Milan','Turin','Florence','Turin','Fermo','Fermo']
df

animal  name      city
0    dog  Paul      Rome
1    dog  Mark     Milan
2    cat  John     Turin
3    dog  Paul  Florence
4  mouse  Paul     Turin
5    cat  Mark     Fermo
6    cat  Mark     Fermo

In [57]:
df['code_animal']=df['animal'].astype('category').cat.codes
df['code_name']=df['name'].astype('category').cat.codes
df['code_city']=df['city'].astype('category').cat.codes
df

animal  name      city  code_animal  code_name  code_city
0    dog  Paul      Rome            1          2          3
1    dog  Mark     Milan            1          1          2
2    cat  John     Turin            0          0          4
3    dog  Paul  Florence            1          2          1
4  mouse  Paul     Turin            2          2          4
5    cat  Mark     Fermo            0          1          0
6    cat  Mark     Fermo            0          1          0

In [58]:
X =  df.as_matrix(columns=['code_animal','code_name','code_city'])
X

array([[1, 2, 3],
       [1, 1, 2],
       [0, 0, 4],
       [1, 2, 1],
       [2, 2, 4],
       [0, 1, 0],
       [0, 1, 0]], dtype=int8)

In [59]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit_transform(X).toarray()

array([[ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.]])

In [60]:
enc.n_values_

array([3, 3, 5])